### PR TITLE
Updated Protocol Pool for Protocol Explorer 

### PR DESCRIPTION
**Pull request by OleanjiKingCode**
New protocols added:
1. IQ.wiki
2. Mirror
3. Developer Dao
4.  Orb 
5. Debank
6.  Fuel
7. Pinata
8. Rarible 
9.  Zapper
10. ImmuneFi
11. FraxFinance

Protocols Upated (Articles):
1. Axelar
2.  Arweave
3. Biconomy
4. celestia
5. EigenLayer
6. Etherspot
7. Filecoin
8. Lens
9. Phala Network
10. The graph
11. ENS
12. Ocean
13. Alchemy
14. Ankr
15. Aragon
16. Audius
17. Farcaster
18. Openzeppelin
19. Pancake
20. Privy
21. Push
22. QuickNode

### CODE REVIEW

**Comment by Rahat-ch** [comment]
This is good so far @OleanjiKingCode I would say lets remove the following: 

Developer Dao
IQ wiki
Orb

we want to make sure any protocls added are specifically dev tools or things that can be added into a tech stack - these are great and especially develoer dao is great but it is not itself a tool. Otherwise looks good!

**Comment by Rahat-ch** [comment]
@Shiv2116 I've asked for a couple items on this pr to be updated once it is you will need to pull the latest so just FYI

**Comment by Shiv2116** [comment]
cool @Rahat-ch i will do it
let me know when u merge this

**Comment by OleanjiKingCode** [comment]
I'll remove them and push the new updatea

**Comment by OleanjiKingCode** [comment]
@Rahat-ch I have remove the protocols you mentioned and then added
- Scroll
- WeaveDB
- Magic

**Comment by Rahat-ch** [comment]
ah woops so we are being chain agnostic at the moment @OleanjiKingCode so not adding chains specifically until we figure out best way to feature them can we remove scroll for now and will merge

**Review by Rahat-ch — APPROVED** [review]

**Comment by Rahat-ch** [comment]
FYI @Shiv2116 this has now been merged

**Pull request merged**
