### PR TITLE
added links to more articles

### PR DESCRIPTION
**Pull request by reetbatra**
Added more links to articles under:
- Farcaster
- Alchemy
- Ankr
- Push

### CODE REVIEW

**Comment by Rahat-ch** [comment]
Hi @reetbatra we recently had some updates on these - can you pull the latest and compare changes if there are any overlaps - feel free to still include anything new that you added

**Comment by reetbatra** [comment]
Ready for review, have resolved conflicts, please take a look

**Comment by Rahat-ch** [comment]
Amazing thanks @reetbatra

**Review by Rahat-ch — APPROVED** [review]

**Comment by Rahat-ch** [comment]
@Shiv2116 FYI merged more article updates

**Pull request merged**
